### ISSUE TITLE
Empty h2 tag in layout

### ISSUE THREAD

**Issue by keraJLi** [Bliss-e-V/webpage#5]
In the [header](https://github.com/Bliss-e-V/webpage/blob/f4d44c384df532a34936fd453fb84c2f702a3e5a/src/components/Header.astro#L27), there is an h2 tag which is never set. This is an SEO issue. @optzGuitar is this intended?

**Comment by optzGuitar** [comment]
I am certain we can remote the h2 and all of the Props.
